import { InsertExpression } from "kysely/dist/cjs/parser/insert-values-parser";
import { UpdateObjectExpression } from "kysely/dist/cjs/parser/update-set-parser";


import { sql } from "kysely";
import { MTGLanguage } from "../../../../../common/enums";
import { DatabaseSchema } from "../../../../database/schema";
import { ICardAdapter } from "../interface";
import { ScryfallCard } from "../../types";

export class CardAdapter implements ICardAdapter {
  public toInsert(scryfall: ScryfallCard): InsertExpression<DatabaseSchema, "card"> {
    return {
      // arena_id: scryfall.arena_id,
      // cardmarket_id: scryfall.cardmarket_id,
      id: scryfall.id,
      // lang: scryfall.lang as MTGLanguage,
      layout: scryfall.layout,
      // mtgo_foil_id: scryfall.mtgo_foil_id,
      // mtgo_id: scryfall.mtgo_id,
      oracle_id: scryfall.oracle_id,
      // prints_search_uri: scryfall.prints_search_uri,
      // rulings_uri: scryfall.rulings_uri,
      scryfall_uri: scryfall.scryfall_uri,
      // tcgplayer_etched_id: scryfall.tcgplayer_etched_id,
      // tcgplayer_id: scryfall.tcgplayer_id,
      // uri: scryfall.uri,
      // cmc: scryfall.cmc,
      // defense:  scryfall.defense,
      // edhrec_rank: scryfall.edhrec_rank,
      // hand_modfier: scryfall.hand_modifier,
      // life_modfier: scryfall.life_modifier,
      // loyalty: scryfall.loyalty,
      // mana_cost: scryfall.mana_cost,
      // name: scryfall.name,
      // oracle_text: scryfall.oracle_text,
      // penny_rank: scryfall.penny_rank,
      // power: scryfall.power,
      // reserved: scryfall.reserved ? 0 : 1,
      // thoughness: scryfall.toughness,
      // type_line: scryfall.type_line,
      // artist: scryfall.artist,
      booster: scryfall.booster ? 0 : 1,
      border: scryfall.border_color,
      card_back_id: scryfall.card_back_id,
      collector_number: scryfall.collector_number,
      content_warning: scryfall.content_warning ? 0 : 1,
      digital: scryfall.digital ? 0 : 1,
      // flavor_name: scryfall.flavor_name,
      // flavor_text: scryfall.flavor_text,
      // frame: scryfall.frame,
      full_art: scryfall.full_art ? 0 : 1,
      // highres_image: scryfall.highres_image ? 0 : 1,
      // illustration_id: scryfall.illustration_id,
      // image_status: scryfall.image_status,
      // oversized: scryfall.oversized ? 0 : 1,
      // printed_name: scryfall.printed_name,
      // printed_text: scryfall.printed_text,
      // printed_type_line: scryfall.printed_type_line,
      // promo: scryfall.promo ? 0 : 1,
      rarity: scryfall.rarity,
      released_at: scryfall.released_at,
      reprint: scryfall.reprint ? 0 : 1,
      // security_stamp: scryfall.security_stamp,
      set_id: scryfall.set_id,
      // story_spotlight: scryfall.story_spotlight ? 0 : 1,
      // textless: scryfall.textless ? 0 : 1,
      // variation: scryfall.variation ? 0 : 1,
      // variation_of: scryfall.variation_of,
      // watermark: scryfall.watermark
    };
  }

  public toUpdate(scryfall: ScryfallCard): UpdateObjectExpression<DatabaseSchema, "card"> {
    return {
      // arena_id: scryfall.arena_id,
      // cardmarket_id: scryfall.cardmarket_id,
      // mtgo_foil_id: scryfall.mtgo_foil_id,
      // mtgo_id: scryfall.mtgo_id,
      oracle_id: scryfall.oracle_id,
      // prints_search_uri: scryfall.prints_search_uri,
      // rulings_uri: scryfall.rulings_uri,
      scryfall_uri: scryfall.scryfall_uri,
      // tcgplayer_etched_id: scryfall.tcgplayer_etched_id,
      // tcgplayer_id: scryfall.tcgplayer_id,
      // uri: scryfall.uri,
      // cmc: scryfall.cmc,
      // defense: scryfall.defense,
      // edhrec_rank: scryfall.edhrec_rank,
      // hand_modfier: scryfall.hand_modifier,
      // life_modfier: scryfall.life_modifier,
      // loyalty: scryfall.loyalty,
      // mana_cost: scryfall.mana_cost,
      // name: scryfall.name,
      // oracle_text: scryfall.oracle_text,
      // penny_rank: scryfall.penny_rank,
      // power: scryfall.power,
      // reserved: scryfall.reserved ? 0 : 1,
      // thoughness: scryfall.toughness,
      // type_line: scryfall.type_line,
      // artist: scryfall.artist,
      booster: scryfall.booster ? 0 : 1,
      border: scryfall.border_color,
      card_back_id: scryfall.card_back_id,
      collector_number: scryfall.collector_number,
      content_warning: scryfall.content_warning ? 0 : 1,
      digital: scryfall.digital ? 0 : 1,
      // flavor_name: scryfall.flavor_name,
      // flavor_text: scryfall.flavor_text,
      // frame: scryfall.frame,
      full_art: scryfall.full_art ? 0 : 1,
      // highres_image: scryfall.highres_image ? 0 : 1,
      // illustration_id: scryfall.illustration_id,
      // image_status: scryfall.image_status,
      // oversized: scryfall.oversized ? 0 : 1,
      // printed_name: scryfall.printed_name,
      // printed_text: scryfall.printed_text,
      // printed_type_line: scryfall.printed_type_line,
      // promo: scryfall.promo ? 0 : 1,
      rarity: scryfall.rarity,
      released_at: scryfall.released_at,
      reprint: scryfall.reprint ? 0 : 1,
      // security_stamp: scryfall.security_stamp,
      set_id: scryfall.set_id,
      // story_spotlight: scryfall.story_spotlight ? 0 : 1,
      // textless: scryfall.textless ? 0 : 1,
      // variation: scryfall.variation ? 0 : 1,
      // variation_of: scryfall.variation_of,
      // watermark: scryfall.watermark,
      last_synced_at: sql`CURRENT_TIMESTAMP`
    };
  }
}
